src/Entity/CarOwner.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarOwnerRepository")
 */
class CarOwner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $middle_name;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $passport_series;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $passport_number;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $license_series;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $license_number;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Car", mappedBy="owner")
     */
    private $cars;

    public function __construct()
    {
        $this->cars = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->middle_name;
    }

    public function setMiddleName(string $middle_name): self
    {
        $this->middle_name = $middle_name;

        return $this;
    }

    public function getPassportSeries(): ?string
    {
        return $this->passport_series;
    }

    public function setPassportSeries(string $passport_series): self
    {
        $this->passport_series = $passport_series;

        return $this;
    }

    public function getPassportNumber(): ?string
    {
        return $this->passport_number;
    }

    public function setPassportNumber(string $passport_number): self
    {
        $this->passport_number = $passport_number;

        return $this;
    }

    public function getLicenseSeries(): ?string
    {
        return $this->license_series;
    }

    public function setLicenseSeries(string $license_series): self
    {
        $this->license_series = $license_series;

        return $this;
    }

    public function getLicenseNumber(): ?string
    {
        return $this->license_number;
    }

    public function setLicenseNumber(string $license_number): self
    {
        $this->license_number = $license_number;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Car[]
     */
    public function getCars(): Collection
    {
        return $this->cars;
    }

    public function addCar(Car $car): self
    {
        if (!$this->cars->contains($car)) {
            $this->cars[] = $car;
            $car->setOwner($this);
        }

        return $this;
    }

    public function removeCar(Car $car): self
    {
        if ($this->cars->contains($car)) {
            $this->cars->removeElement($car);
            // set the owning side to null (unless already changed)
            if ($car->getOwner() === $this) {
                $car->setOwner(null);
            }
        }

        return $this;
    }
}

templates/car_owner/_delete_form.html.twig
<form method="post" action="{{ path('car_owner_delete', {'id': car_owner.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car_owner.id) }}">
    <button class="btn">Delete</button>
</form>

templates/car_owner/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/car_owner/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CarOwner{% endblock %}

{% block body %}
    <h1>Edit CarOwner</h1>

    {{ include('car_owner/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('car_owner_index') }}">back to list</a>

    {{ include('car_owner/_delete_form.html.twig') }}
{% endblock %}

templates/car_owner/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarOwner index{% endblock %}

{% block body %}
    <h1>CarOwner index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Middle_name</th>
                <th>Passport_series</th>
                <th>Passport_number</th>
                <th>License_series</th>
                <th>License_number</th>
                <th>Phone</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for car_owner in car_owners %}
            <tr>
                <td>{{ car_owner.id }}</td>
                <td>{{ car_owner.firstName }}</td>
                <td>{{ car_owner.lastName }}</td>
                <td>{{ car_owner.middleName }}</td>
                <td>{{ car_owner.passportSeries }}</td>
                <td>{{ car_owner.passportNumber }}</td>
                <td>{{ car_owner.licenseSeries }}</td>
                <td>{{ car_owner.licenseNumber }}</td>
                <td>{{ car_owner.phone }}</td>
                <td>
                    <a href="{{ path('car_owner_show', {'id': car_owner.id}) }}">show</a>
                    <a href="{{ path('car_owner_edit', {'id': car_owner.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('car_owner_new') }}">Create new</a>
{% endblock %}

templates/car_owner/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CarOwner{% endblock %}

{% block body %}
    <h1>Create new CarOwner</h1>

    {{ include('car_owner/_form.html.twig') }}

    <a href="{{ path('car_owner_index') }}">back to list</a>
{% endblock %}

templates/car_owner/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarOwner{% endblock %}

{% block body %}
    <h1>CarOwner</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ car_owner.id }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ car_owner.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ car_owner.lastName }}</td>
            </tr>
            <tr>
                <th>Middle_name</th>
                <td>{{ car_owner.middleName }}</td>
            </tr>
            <tr>
                <th>Passport_series</th>
                <td>{{ car_owner.passportSeries }}</td>
            </tr>
            <tr>
                <th>Passport_number</th>
                <td>{{ car_owner.passportNumber }}</td>
            </tr>
            <tr>
                <th>License_series</th>
                <td>{{ car_owner.licenseSeries }}</td>
            </tr>
            <tr>
                <th>License_number</th>
                <td>{{ car_owner.licenseNumber }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ car_owner.phone }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('car_owner_index') }}">back to list</a>

    <a href="{{ path('car_owner_edit', {'id': car_owner.id}) }}">edit</a>

    {{ include('car_owner/_delete_form.html.twig') }}
{% endblock %}